### ISSUE TITLE
Potential memory leaks

### ISSUE THREAD

**Issue by chenxx08** [aerys/minko#227]
```
std::weak_ptr<Canvas> wCanvas;
{
    auto canvas = Canvas::create("Minko Example - Cube");
    wCanvas = canvas;
    ...
    canvas->run();
}
auto useCount = wCanvas.use_count();
```

The useCount is not zero, the canvas and other objects(sceneManager, root, etc.) didn't disposed.
If I create the Minko window several times and then close in my program, memory usage will be more and more.

Sorry for my poor English.

**Comment by warrenseine** [comment]
Indeed.

However, since re-creating multiple SDL windows is a very specific use case, we don't intend to fix this. A pull request is welcome!

**Comment by promethe42** [comment]
@warrenseine I think we've made lots of memory improvements for some of our latest customer projects and the 3D player on minko.io. Are those changes available on dev ?

**Comment by chenxx08** [comment]
If Minko is not just for game, the case should be more common. I use it on the Android and iOS to view 3D model. User maybe repeatedly navigate to the 3D model view.

This problem should be caused by circular reference that is very common in this project. Do you have any suggestion to solve this problem. Thank you!

**Comment by promethe42** [comment]
> This problem should be caused by circular reference that is very common in this project. Do you have any suggestion to solve this problem. Thank you!

This is exactly the kind of things we fixed using `std::weak_ptr` for example. @warrenseine ?

**Comment by warrenseine** [comment]
In that specific case, I think I know where the leak is. We keep the last allocated canvas in a static variable. See `Canvas::defaultCanvas()`.

@promethe42 Changing this to a `weak_ptr` should safely fix the issue. @chenxx08 Can you try and tell us if the leak goes away?

**Comment by chenxx08** [comment]
The problem still exsit. It's caused by circular reference. As shown in the following code.

//Canva.hpp
class Canva:
{
    ...
    std::shared_ptr<input::SDLMouse>                                        _mouse;
    ...
}

//Canva.cpp
void
Canvas::initializeInputs()
{
    _mouse = input::SDLMouse::create(shared_from_this());
   ...
}

//Mouse.hpp
class Mouse
{
    ...
    std::shared_ptr<AbstractCanvas>	_canvas;
}

//Mouse.cpp
Mouse::Mouse(std::shared_ptr<AbstractCanvas> canvas) :
    _canvas(canvas),
   ...
{
}

Touch, Joystick and some other class also have the same problem. Some class like Node class fixed in Dev branch by use weak_ptr, some class still not use weak_ptr.

And some code like this may also cause circular reference.

_classField = someSignal.connect(std::bind(
		&Class::someMethod,
		std::dynamic_pointer_cast<Class>(shared_from_this()),
                ...
	));

It's can be modified like this:
_classField = someSignal.connect(std::bind(
		&Class::someMethod,
		this,
                ...
	));

**Comment by promethe42** [comment]
Did you test the latest version on dev ?
